# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20171221_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showhelloworld',
            options={'verbose_name': 'testApp', 'verbose_name_plural': 'testApps'},
        ),
    ]
